apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 80
      port: 3000
      nodePort: 30000
