name: Tech Challenge - Deploy Infrastructure - GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true

      - name: Install gke-gcloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: GKE credentials
        run: |-
          gcloud container clusters get-credentials tech-challenge-producao --zone us-central1 --project ${{ secrets.PROJECT_ID }}

      - name: Deploy
        run: |-
          kubectl apply -f k8s/
